CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_USE_LABEL=y
CONFIG_CHECK_INIT_PRIORITIES=n
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT_CST816S=y
CONFIG_INPUT_CST816S_INTERRUPT=y
CONFIG_ZMK_SPLIT=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_KEYBOARD_NAME="Enki Counter"

# PMW3610 optical sensor settings
CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=n
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=y
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=14
CONFIG_PMW3610_LOG_LEVEL_WRN=y
# CONFIG_INPUT_PMW3610_INIT_PRIORITY=80
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=100
